apiVersion: v1
kind: Pod
metadata:
  labels:
    app: secret-poc-v0
    deployment: secret-poc-v0-3
    deploymentconfig: secret-poc-v0
  name: secret-poc-v0-3
  namespace: project-from-client
  
  
spec:
  containers:
    - env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: my-own-secret
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: my-own-secret
     
      volumeMounts:
        - mountPath: /apipassword
          name: secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: api-password    
 