name: TEST Action
on:
  workflow_dispatch:
    inputs:
      tagVersion:
        description: 'Image Tag'     
        required: true
        default: 'latest'
      Env:
        type: choice
        description: 'Deployed Env'     
        required: true
        options: 
        - dv
        - it01
        - it02
        - it03
        - it04
        - pr
      
      
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    #environment: ST
    steps:
      - name: inputs are
        run: echo "${{ github.event.inputs.env }},  ${{ github.event.inputs.tagVersion }"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}
