name: TEST Action
on:
  workflow_dispatch:
    inputs:
      tagVersion:
        description: 'Image Tag'     
        required: true
        default: 'latest'
      Env:
        type: choice
        description: 'Deployed Env'     
        required: true
        options: 
        -  
        - dv
        - it01
        - it02
        - it03
        - it04
        - pr

env:
  DELIVERY_PIPELINE_NAME: backfill-to-${{ github.event.inputs.Env }}
      
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    #environment: ST
    steps:
      - name: inputs are
        run: echo "${{ github.event.inputs.Env }},  ${{ github.event.inputs.tagVersion }}"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}
      - name: test yaml file 
        run: |-
          echo ' 
          apiVersion: deploy.cloud.google.com/v1
          kind: DeliveryPipeline
          metadata:
           name: ${{ env.DELIVERY_PIPELINE_NAME }}
           annotations: {}
           labels: {}
          description: CICD demo deploy pipeline
          serialPipeline:
           stages:
           - targetId: ${{github.event.inputs.Env}}
           profiles: [${{github.event.inputs.Env}}]
          '
          cat temp.yaml
      
